#!/bin/sh
# TTY Color Scheme
# Generated by 'wpg-m3' - Material 3 Color Scheme
[ "${TERM:-none}" = "linux" ] && \
    printf '%b' '\e]P0#14140e
                 \e]P1#690005
                 \e]P2#cacb76
                 \e]P3#494a00
                 \e]P4#616218
                 \e]P5#36352e
                 \e]P6#4b4b2b
                 \e]P7#cacb76
                 \e]P8#939181
                 \e]P9#ffb4ab
                 \e]PA#b9eaff
                 \e]PB#e7e78f
                 \e]PC#cacb76
                 \e]PD#88d0ed
                 \e]PE#88d0ed
                 \e]PF#e6e2d8
                 \ec'
